### ISSUE TITLE
window.webkitStorageInfo' is deprecated

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#574]
This warning is back in the browser...

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
```

Seems to only happen when I `buildStatic()` my code, so I'm posting it here.

Tried putting this into both `jspm.browser.js` and `jspm.config.js`:

```
	meta: {
		"core-js/modules/$.global.js": {
			"esmExports": false
		}
	}
```

Oddly, if I comment out the meta stuff above from both files, it doesn't happen when running unbundled, just with my bundle.

**Comment by lookfirst** [comment]
Changing it to:

```
    "core-js/modules/_global.js": {
```

Doesn't help.

**Comment by guybedford** [comment]
Thanks, this was a regression when updating from SystemJS. Fixed in https://github.com/systemjs/builder/commit/8c16e95b1c27c1a0ed7684ec2c46b8e8dbbcb392 and also fixed the reason for the regression as well.

**Comment by lookfirst** [comment]
So do I need the above meta or can I do without it now? 

How do I take advantage of this before release again?

**Comment by lookfirst** [comment]
btw, I'm on 0.17 now, so far so good.

**Comment by guybedford** [comment]
Nice, great to hear that. Yes you can leave out the meta with this fix - the point was that we don't support the meta for static builds pending https://github.com/systemjs/builder/issues/338 so this was the workaround approach.

**Comment by lookfirst** [comment]
@guybedford Just tried it...

```
    Looking up loader files...
       system.js
       system-polyfills.js
       system-polyfills.src.js
       system.js.map
       system.src.js
       system-polyfills.js.map

     Using loader versions:
       systemjs@master
```

Then built my bundle and still seeing the message in the logs

**Comment by lookfirst** [comment]
Ignore last comment.

**Comment by guybedford** [comment]
Released in 0.15.17.
